CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_101:130-238	Bart	PER	SIMPSONS_101:232-237	0.7792	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_131:113-239	Bart Simpson	PER	SIMPSONS_131:183-196	0.2588	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_158:205-327	Bart	PER	SIMPSONS_158:246-251	0.4200	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_166:249-367	Bart	PER	SIMPSONS_166:138-143	0.1948	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_190:145-297	Bart Simpson	PER	SIMPSONS_190:211-224	0.4751	:Entity102
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_123:163-296	Springfield Elementary School	ORG	SIMPSONS_123:138-168	0.9718	:Entity110
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_123:163-296	Springfield Elementary School	ORG	SIMPSONS_123:138-168	0.9718	:Entity110
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_123:163-296	Springfield Elementary School	ORG	SIMPSONS_123:138-168	0.9718	:Entity110
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_123:163-296	Springfield Elementary School	ORG	SIMPSONS_123:138-168	0.9718	:Entity110
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_123:163-296	Springfield Elementary School	ORG	SIMPSONS_123:138-168	0.9718	:Entity110
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_137:225-382	Springfield Elementary School	ORG	SIMPSONS_137:111-141	0.6805	:Entity110
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_137:225-382	Springfield Elementary School	ORG	SIMPSONS_137:111-141	0.6805	:Entity110
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_137:225-382	Springfield Elementary School	ORG	SIMPSONS_137:111-141	0.6805	:Entity110
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_137:225-382	Springfield Elementary School	ORG	SIMPSONS_137:111-141	0.6805	:Entity110
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_137:225-382	Springfield Elementary School	ORG	SIMPSONS_137:111-141	0.6805	:Entity110
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_157:166-275	Springfield Elementary School	ORG	SIMPSONS_157:170-200	0.2959	:Entity110
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_157:166-275	Springfield Elementary School	ORG	SIMPSONS_157:170-200	0.2959	:Entity110
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_157:166-275	Springfield Elementary School	ORG	SIMPSONS_157:170-200	0.2959	:Entity110
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_157:166-275	Springfield Elementary School	ORG	SIMPSONS_157:170-200	0.2959	:Entity110
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_157:166-275	Springfield Elementary School	ORG	SIMPSONS_157:170-200	0.2959	:Entity110
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_158:120-272	Springfield Elementary School	ORG	SIMPSONS_158:229-259	0.4837	:Entity110
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_158:120-272	Springfield Elementary School	ORG	SIMPSONS_158:229-259	0.4837	:Entity110
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_158:120-272	Springfield Elementary School	ORG	SIMPSONS_158:229-259	0.4837	:Entity110
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_158:120-272	Springfield Elementary School	ORG	SIMPSONS_158:229-259	0.4837	:Entity110
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_158:120-272	Springfield Elementary School	ORG	SIMPSONS_158:229-259	0.4837	:Entity110
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_160:169-286	Springfield Elementary School	ORG	SIMPSONS_160:185-215	0.5343	:Entity110
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_160:169-286	Springfield Elementary School	ORG	SIMPSONS_160:185-215	0.5343	:Entity110
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_160:169-286	Springfield Elementary School	ORG	SIMPSONS_160:185-215	0.5343	:Entity110
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_160:169-286	Springfield Elementary School	ORG	SIMPSONS_160:185-215	0.5343	:Entity110
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_160:169-286	Springfield Elementary School	ORG	SIMPSONS_160:185-215	0.5343	:Entity110
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_104:190-302	Springfield High School	ORG	SIMPSONS_104:114-138	0.8444	:Entity111
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_104:190-302	Springfield High School	ORG	SIMPSONS_104:114-138	0.8444	:Entity111
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_104:190-302	Springfield High School	ORG	SIMPSONS_104:114-138	0.8444	:Entity111
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_104:190-302	Springfield High School	ORG	SIMPSONS_104:114-138	0.8444	:Entity111
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_104:190-302	Springfield High School	ORG	SIMPSONS_104:114-138	0.8444	:Entity111
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_151:174-292	Springfield High School	ORG	SIMPSONS_151:150-174	0.4724	:Entity111
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_151:174-292	Springfield High School	ORG	SIMPSONS_151:150-174	0.4724	:Entity111
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_151:174-292	Springfield High School	ORG	SIMPSONS_151:150-174	0.4724	:Entity111
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_151:174-292	Springfield High School	ORG	SIMPSONS_151:150-174	0.4724	:Entity111
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_151:174-292	Springfield High School	ORG	SIMPSONS_151:150-174	0.4724	:Entity111
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_153:231-387	Springfield High School	ORG	SIMPSONS_153:148-172	0.5387	:Entity111
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_153:231-387	Springfield High School	ORG	SIMPSONS_153:148-172	0.5387	:Entity111
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_153:231-387	Springfield High School	ORG	SIMPSONS_153:148-172	0.5387	:Entity111
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_153:231-387	Springfield High School	ORG	SIMPSONS_153:148-172	0.5387	:Entity111
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_153:231-387	Springfield High School	ORG	SIMPSONS_153:148-172	0.5387	:Entity111
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_166:244-383	Springfield High School	ORG	SIMPSONS_166:151-175	0.9343	:Entity111
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_166:244-383	Springfield High School	ORG	SIMPSONS_166:151-175	0.9343	:Entity111
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_166:244-383	Springfield High School	ORG	SIMPSONS_166:151-175	0.9343	:Entity111
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_166:244-383	Springfield High School	ORG	SIMPSONS_166:151-175	0.9343	:Entity111
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_166:244-383	Springfield High School	ORG	SIMPSONS_166:151-175	0.9343	:Entity111
CSSF17_ENG_afddc4ed21_729d7f6f2d47	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_177:169-317	Springfield High School	ORG	SIMPSONS_177:105-129	0.0370	:Entity111
CSSF17_ENG_afddc4ed21_af230dac70ef	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_177:169-317	Springfield High School	ORG	SIMPSONS_177:105-129	0.0370	:Entity111
CSSF17_ENG_afddc4ed21_0d2feb6ef2ff	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_177:169-317	Springfield High School	ORG	SIMPSONS_177:105-129	0.0370	:Entity111
CSSF17_ENG_afddc4ed21_3df89ca5aceb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_177:169-317	Springfield High School	ORG	SIMPSONS_177:105-129	0.0370	:Entity111
CSSF17_ENG_afddc4ed21_48f327d3b6eb	per:schools_attended	SCORER_TS_PARENT_INCORRECT_CHILD_CORRECT	SIMPSONS_177:169-317	Springfield High School	ORG	SIMPSONS_177:105-129	0.0370	:Entity111
