CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_101:125-224	Lisa	PER	SIMPSONS_101:114-119	0.5675	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_153:163-319	Lisa	PER	SIMPSONS_153:194-199	0.8624	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_161:237-383	Bart	PER	SIMPSONS_161:185-190	0.9976	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_163:111-258	Bart	PER	SIMPSONS_163:115-120	0.1422	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_172:116-218	Bart	PER	SIMPSONS_172:145-150	0.5391	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_101:226-336	Lisa Simpson	PER	SIMPSONS_101:198-211	0.4029	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_132:177-279	Lisa Simpson	PER	SIMPSONS_132:136-149	0.7648	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_170:193-296	Lisa Simpson	PER	SIMPSONS_170:197-210	0.5654	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_178:184-302	Bart Simpson	PER	SIMPSONS_178:182-195	0.3867	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_189:173-316	Lisa Simpson	PER	SIMPSONS_189:218-231	0.0863	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_110:137-284	Lisa Simpson	PER	SIMPSONS_110:165-178	0.6920	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_116:216-325	Lisa Simpson	PER	SIMPSONS_116:100-113	0.4173	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_136:169-276	Lisa Simpson	PER	SIMPSONS_136:174-187	0.2578	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_188:146-262	Lisa Simpson	PER	SIMPSONS_188:233-246	0.4014	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_195:103-255	Lisa Simpson	PER	SIMPSONS_195:140-153	0.1712	:Entity104
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_103:132-241	Springfield Elementary School	ORG	SIMPSONS_103:197-227	0.3543	:Entity110
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_103:132-241	Springfield Elementary School	ORG	SIMPSONS_103:197-227	0.3543	:Entity110
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_103:132-241	Springfield Elementary School	ORG	SIMPSONS_103:197-227	0.3543	:Entity110
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_103:132-241	Springfield Elementary School	ORG	SIMPSONS_103:197-227	0.3543	:Entity110
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_103:132-241	Springfield Elementary School	ORG	SIMPSONS_103:197-227	0.3543	:Entity110
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:151-272	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.9369	:Entity110
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:151-272	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.9369	:Entity110
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:151-272	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.9369	:Entity110
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:151-272	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.9369	:Entity110
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:151-272	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.9369	:Entity110
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:209-359	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.0851	:Entity110
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:209-359	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.0851	:Entity110
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:209-359	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.0851	:Entity110
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:209-359	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.0851	:Entity110
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_107:209-359	Springfield Elementary School	ORG	SIMPSONS_107:236-266	0.0851	:Entity110
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_135:155-269	Springfield Elementary School	ORG	SIMPSONS_135:243-273	0.7648	:Entity110
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_135:155-269	Springfield Elementary School	ORG	SIMPSONS_135:243-273	0.7648	:Entity110
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_135:155-269	Springfield Elementary School	ORG	SIMPSONS_135:243-273	0.7648	:Entity110
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_135:155-269	Springfield Elementary School	ORG	SIMPSONS_135:243-273	0.7648	:Entity110
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_135:155-269	Springfield Elementary School	ORG	SIMPSONS_135:243-273	0.7648	:Entity110
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_137:208-359	Springfield Elementary School	ORG	SIMPSONS_137:113-143	0.6755	:Entity110
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_137:208-359	Springfield Elementary School	ORG	SIMPSONS_137:113-143	0.6755	:Entity110
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_137:208-359	Springfield Elementary School	ORG	SIMPSONS_137:113-143	0.6755	:Entity110
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_137:208-359	Springfield Elementary School	ORG	SIMPSONS_137:113-143	0.6755	:Entity110
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_137:208-359	Springfield Elementary School	ORG	SIMPSONS_137:113-143	0.6755	:Entity110
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_144:191-290	Springfield Elementary School	ORG	SIMPSONS_144:156-186	0.5049	:Entity110
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_144:191-290	Springfield Elementary School	ORG	SIMPSONS_144:156-186	0.5049	:Entity110
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_144:191-290	Springfield Elementary School	ORG	SIMPSONS_144:156-186	0.5049	:Entity110
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_144:191-290	Springfield Elementary School	ORG	SIMPSONS_144:156-186	0.5049	:Entity110
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_144:191-290	Springfield Elementary School	ORG	SIMPSONS_144:156-186	0.5049	:Entity110
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_145:190-318	Springfield Elementary School	ORG	SIMPSONS_145:112-142	0.8051	:Entity110
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_145:190-318	Springfield Elementary School	ORG	SIMPSONS_145:112-142	0.8051	:Entity110
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_145:190-318	Springfield Elementary School	ORG	SIMPSONS_145:112-142	0.8051	:Entity110
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_145:190-318	Springfield Elementary School	ORG	SIMPSONS_145:112-142	0.8051	:Entity110
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_145:190-318	Springfield Elementary School	ORG	SIMPSONS_145:112-142	0.8051	:Entity110
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_156:185-305	Springfield Elementary School	ORG	SIMPSONS_156:192-222	0.6422	:Entity110
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_156:185-305	Springfield Elementary School	ORG	SIMPSONS_156:192-222	0.6422	:Entity110
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_156:185-305	Springfield Elementary School	ORG	SIMPSONS_156:192-222	0.6422	:Entity110
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_156:185-305	Springfield Elementary School	ORG	SIMPSONS_156:192-222	0.6422	:Entity110
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_156:185-305	Springfield Elementary School	ORG	SIMPSONS_156:192-222	0.6422	:Entity110
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_183:126-242	Springfield Elementary School	ORG	SIMPSONS_183:145-175	0.3438	:Entity110
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_183:126-242	Springfield Elementary School	ORG	SIMPSONS_183:145-175	0.3438	:Entity110
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_183:126-242	Springfield Elementary School	ORG	SIMPSONS_183:145-175	0.3438	:Entity110
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_183:126-242	Springfield Elementary School	ORG	SIMPSONS_183:145-175	0.3438	:Entity110
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_183:126-242	Springfield Elementary School	ORG	SIMPSONS_183:145-175	0.3438	:Entity110
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:161-299	Springfield Elementary School	ORG	SIMPSONS_187:172-202	0.5694	:Entity110
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:161-299	Springfield Elementary School	ORG	SIMPSONS_187:172-202	0.5694	:Entity110
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:161-299	Springfield Elementary School	ORG	SIMPSONS_187:172-202	0.5694	:Entity110
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:161-299	Springfield Elementary School	ORG	SIMPSONS_187:172-202	0.5694	:Entity110
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:161-299	Springfield Elementary School	ORG	SIMPSONS_187:172-202	0.5694	:Entity110
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_188:108-223	Springfield Elementary School	ORG	SIMPSONS_188:131-161	0.5323	:Entity110
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_188:108-223	Springfield Elementary School	ORG	SIMPSONS_188:131-161	0.5323	:Entity110
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_188:108-223	Springfield Elementary School	ORG	SIMPSONS_188:131-161	0.5323	:Entity110
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_188:108-223	Springfield Elementary School	ORG	SIMPSONS_188:131-161	0.5323	:Entity110
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_188:108-223	Springfield Elementary School	ORG	SIMPSONS_188:131-161	0.5323	:Entity110
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_189:168-269	Springfield Elementary School	ORG	SIMPSONS_189:187-217	0.3919	:Entity110
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_189:168-269	Springfield Elementary School	ORG	SIMPSONS_189:187-217	0.3919	:Entity110
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_189:168-269	Springfield Elementary School	ORG	SIMPSONS_189:187-217	0.3919	:Entity110
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_189:168-269	Springfield Elementary School	ORG	SIMPSONS_189:187-217	0.3919	:Entity110
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_189:168-269	Springfield Elementary School	ORG	SIMPSONS_189:187-217	0.3919	:Entity110
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_191:130-246	Springfield Elementary School	ORG	SIMPSONS_191:102-132	0.5466	:Entity110
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_191:130-246	Springfield Elementary School	ORG	SIMPSONS_191:102-132	0.5466	:Entity110
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_191:130-246	Springfield Elementary School	ORG	SIMPSONS_191:102-132	0.5466	:Entity110
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_191:130-246	Springfield Elementary School	ORG	SIMPSONS_191:102-132	0.5466	:Entity110
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_191:130-246	Springfield Elementary School	ORG	SIMPSONS_191:102-132	0.5466	:Entity110
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_197:165-267	Springfield Elementary School	ORG	SIMPSONS_197:170-200	0.5075	:Entity110
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_197:165-267	Springfield Elementary School	ORG	SIMPSONS_197:170-200	0.5075	:Entity110
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_197:165-267	Springfield Elementary School	ORG	SIMPSONS_197:170-200	0.5075	:Entity110
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_197:165-267	Springfield Elementary School	ORG	SIMPSONS_197:170-200	0.5075	:Entity110
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_197:165-267	Springfield Elementary School	ORG	SIMPSONS_197:170-200	0.5075	:Entity110
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_198:166-324	Springfield Elementary School	ORG	SIMPSONS_198:249-279	0.4126	:Entity110
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_198:166-324	Springfield Elementary School	ORG	SIMPSONS_198:249-279	0.4126	:Entity110
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_198:166-324	Springfield Elementary School	ORG	SIMPSONS_198:249-279	0.4126	:Entity110
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_198:166-324	Springfield Elementary School	ORG	SIMPSONS_198:249-279	0.4126	:Entity110
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_198:166-324	Springfield Elementary School	ORG	SIMPSONS_198:249-279	0.4126	:Entity110
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_101:116-224	Springfield High School	ORG	SIMPSONS_101:196-220	0.0725	:Entity111
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_101:116-224	Springfield High School	ORG	SIMPSONS_101:196-220	0.0725	:Entity111
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_101:116-224	Springfield High School	ORG	SIMPSONS_101:196-220	0.0725	:Entity111
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_101:116-224	Springfield High School	ORG	SIMPSONS_101:196-220	0.0725	:Entity111
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_101:116-224	Springfield High School	ORG	SIMPSONS_101:196-220	0.0725	:Entity111
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_104:204-314	Springfield High School	ORG	SIMPSONS_104:176-200	0.8577	:Entity111
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_104:204-314	Springfield High School	ORG	SIMPSONS_104:176-200	0.8577	:Entity111
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_104:204-314	Springfield High School	ORG	SIMPSONS_104:176-200	0.8577	:Entity111
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_104:204-314	Springfield High School	ORG	SIMPSONS_104:176-200	0.8577	:Entity111
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_104:204-314	Springfield High School	ORG	SIMPSONS_104:176-200	0.8577	:Entity111
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_115:104-233	Springfield High School	ORG	SIMPSONS_115:225-249	0.6056	:Entity111
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_115:104-233	Springfield High School	ORG	SIMPSONS_115:225-249	0.6056	:Entity111
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_115:104-233	Springfield High School	ORG	SIMPSONS_115:225-249	0.6056	:Entity111
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_115:104-233	Springfield High School	ORG	SIMPSONS_115:225-249	0.6056	:Entity111
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_115:104-233	Springfield High School	ORG	SIMPSONS_115:225-249	0.6056	:Entity111
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_116:115-242	Springfield High School	ORG	SIMPSONS_116:118-142	0.5727	:Entity111
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_116:115-242	Springfield High School	ORG	SIMPSONS_116:118-142	0.5727	:Entity111
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_116:115-242	Springfield High School	ORG	SIMPSONS_116:118-142	0.5727	:Entity111
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_116:115-242	Springfield High School	ORG	SIMPSONS_116:118-142	0.5727	:Entity111
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_116:115-242	Springfield High School	ORG	SIMPSONS_116:118-142	0.5727	:Entity111
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_118:156-310	Springfield High School	ORG	SIMPSONS_118:198-222	0.1277	:Entity111
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_118:156-310	Springfield High School	ORG	SIMPSONS_118:198-222	0.1277	:Entity111
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_118:156-310	Springfield High School	ORG	SIMPSONS_118:198-222	0.1277	:Entity111
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_118:156-310	Springfield High School	ORG	SIMPSONS_118:198-222	0.1277	:Entity111
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_118:156-310	Springfield High School	ORG	SIMPSONS_118:198-222	0.1277	:Entity111
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_148:207-324	Springfield High School	ORG	SIMPSONS_148:154-178	0.1185	:Entity111
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_148:207-324	Springfield High School	ORG	SIMPSONS_148:154-178	0.1185	:Entity111
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_148:207-324	Springfield High School	ORG	SIMPSONS_148:154-178	0.1185	:Entity111
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_148:207-324	Springfield High School	ORG	SIMPSONS_148:154-178	0.1185	:Entity111
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_148:207-324	Springfield High School	ORG	SIMPSONS_148:154-178	0.1185	:Entity111
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:182-302	Springfield High School	ORG	SIMPSONS_149:123-147	0.8171	:Entity111
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:182-302	Springfield High School	ORG	SIMPSONS_149:123-147	0.8171	:Entity111
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:182-302	Springfield High School	ORG	SIMPSONS_149:123-147	0.8171	:Entity111
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:182-302	Springfield High School	ORG	SIMPSONS_149:123-147	0.8171	:Entity111
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:182-302	Springfield High School	ORG	SIMPSONS_149:123-147	0.8171	:Entity111
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:168-268	Springfield High School	ORG	SIMPSONS_149:123-147	0.4418	:Entity111
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:168-268	Springfield High School	ORG	SIMPSONS_149:123-147	0.4418	:Entity111
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:168-268	Springfield High School	ORG	SIMPSONS_149:123-147	0.4418	:Entity111
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:168-268	Springfield High School	ORG	SIMPSONS_149:123-147	0.4418	:Entity111
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_149:168-268	Springfield High School	ORG	SIMPSONS_149:123-147	0.4418	:Entity111
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_159:145-289	Springfield High School	ORG	SIMPSONS_159:210-234	0.8733	:Entity111
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_159:145-289	Springfield High School	ORG	SIMPSONS_159:210-234	0.8733	:Entity111
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_159:145-289	Springfield High School	ORG	SIMPSONS_159:210-234	0.8733	:Entity111
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_159:145-289	Springfield High School	ORG	SIMPSONS_159:210-234	0.8733	:Entity111
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_159:145-289	Springfield High School	ORG	SIMPSONS_159:210-234	0.8733	:Entity111
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_173:220-336	Springfield High School	ORG	SIMPSONS_173:129-153	0.1558	:Entity111
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_173:220-336	Springfield High School	ORG	SIMPSONS_173:129-153	0.1558	:Entity111
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_173:220-336	Springfield High School	ORG	SIMPSONS_173:129-153	0.1558	:Entity111
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_173:220-336	Springfield High School	ORG	SIMPSONS_173:129-153	0.1558	:Entity111
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_173:220-336	Springfield High School	ORG	SIMPSONS_173:129-153	0.1558	:Entity111
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_180:215-330	Springfield High School	ORG	SIMPSONS_180:239-263	0.1833	:Entity111
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_180:215-330	Springfield High School	ORG	SIMPSONS_180:239-263	0.1833	:Entity111
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_180:215-330	Springfield High School	ORG	SIMPSONS_180:239-263	0.1833	:Entity111
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_180:215-330	Springfield High School	ORG	SIMPSONS_180:239-263	0.1833	:Entity111
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_180:215-330	Springfield High School	ORG	SIMPSONS_180:239-263	0.1833	:Entity111
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_184:182-312	Springfield High School	ORG	SIMPSONS_184:191-215	0.5559	:Entity111
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_184:182-312	Springfield High School	ORG	SIMPSONS_184:191-215	0.5559	:Entity111
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_184:182-312	Springfield High School	ORG	SIMPSONS_184:191-215	0.5559	:Entity111
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_184:182-312	Springfield High School	ORG	SIMPSONS_184:191-215	0.5559	:Entity111
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_184:182-312	Springfield High School	ORG	SIMPSONS_184:191-215	0.5559	:Entity111
CSSF17_ENG_afddc4ed21_2f7818a4b942	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:137-237	Springfield High School	ORG	SIMPSONS_187:113-137	0.9370	:Entity111
CSSF17_ENG_afddc4ed21_1eddf58e01b6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:137-237	Springfield High School	ORG	SIMPSONS_187:113-137	0.9370	:Entity111
CSSF17_ENG_afddc4ed21_ff060fa2398b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:137-237	Springfield High School	ORG	SIMPSONS_187:113-137	0.9370	:Entity111
CSSF17_ENG_afddc4ed21_77bc3db05d62	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:137-237	Springfield High School	ORG	SIMPSONS_187:113-137	0.9370	:Entity111
CSSF17_ENG_afddc4ed21_6380d1a80ca1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_187:137-237	Springfield High School	ORG	SIMPSONS_187:113-137	0.9370	:Entity111
CSSF17_ENG_afddc4ed21_cb8568c571b5	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_193:123-242	Springfield High School	ORG	SIMPSONS_193:101-125	0.3007	:Entity111
CSSF17_ENG_afddc4ed21_da9bfaeece35	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_193:123-242	Springfield High School	ORG	SIMPSONS_193:101-125	0.3007	:Entity111
CSSF17_ENG_afddc4ed21_70f02c8c32af	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_193:123-242	Springfield High School	ORG	SIMPSONS_193:101-125	0.3007	:Entity111
CSSF17_ENG_afddc4ed21_ff536aa224f1	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_193:123-242	Springfield High School	ORG	SIMPSONS_193:101-125	0.3007	:Entity111
CSSF17_ENG_afddc4ed21_0aeb5a6b4de9	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_193:123-242	Springfield High School	ORG	SIMPSONS_193:101-125	0.3007	:Entity111
CSSF17_ENG_afddc4ed21_08e3ae1a1723	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_196:173-298	Springfield High School	ORG	SIMPSONS_196:212-236	0.8465	:Entity111
CSSF17_ENG_afddc4ed21_027894de4d1b	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_196:173-298	Springfield High School	ORG	SIMPSONS_196:212-236	0.8465	:Entity111
CSSF17_ENG_afddc4ed21_d2c1ebbc68cc	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_196:173-298	Springfield High School	ORG	SIMPSONS_196:212-236	0.8465	:Entity111
CSSF17_ENG_afddc4ed21_92a4ebcff8ec	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_196:173-298	Springfield High School	ORG	SIMPSONS_196:212-236	0.8465	:Entity111
CSSF17_ENG_afddc4ed21_703cfaad2eee	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT	SIMPSONS_196:173-298	Springfield High School	ORG	SIMPSONS_196:212-236	0.8465	:Entity111
