CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_108:142-299	Bart	PER	SIMPSONS_108:212-217	0.5504	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_125:131-256	Bart	PER	SIMPSONS_125:104-109	0.7901	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:161-268	Bart	PER	SIMPSONS_128:123-128	0.1789	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_159:161-264	Bart	PER	SIMPSONS_159:216-221	0.1724	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_183:112-214	Bart	PER	SIMPSONS_183:196-201	0.4556	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:107-210	Lisa Simpson	PER	SIMPSONS_113:201-214	0.1237	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_132:196-313	Bart Simpson	PER	SIMPSONS_132:115-128	0.4396	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_171:142-248	Lisa Simpson	PER	SIMPSONS_171:218-231	0.1753	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_193:219-339	Bart Simpson	PER	SIMPSONS_193:155-168	0.7764	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_196:157-263	Lisa Simpson	PER	SIMPSONS_196:166-179	0.7998	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_100:164-289	Lisa Simpson	PER	SIMPSONS_100:167-180	0.0483	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_119:194-332	Lisa Simpson	PER	SIMPSONS_119:158-171	0.6893	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_127:181-304	Lisa Simpson	PER	SIMPSONS_127:129-142	0.0521	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_130:237-347	Lisa Simpson	PER	SIMPSONS_130:195-208	0.1089	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_178:230-358	Lisa Simpson	PER	SIMPSONS_178:109-122	0.5174	:Entity104
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_108:236-374	Springfield Elementary School	ORG	SIMPSONS_108:128-158	0.9102	:Entity110
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_108:236-374	Springfield Elementary School	ORG	SIMPSONS_108:128-158	0.9102	:Entity110
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_108:236-374	Springfield Elementary School	ORG	SIMPSONS_108:128-158	0.9102	:Entity110
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_108:236-374	Springfield Elementary School	ORG	SIMPSONS_108:128-158	0.9102	:Entity110
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_108:236-374	Springfield Elementary School	ORG	SIMPSONS_108:128-158	0.9102	:Entity110
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:240-358	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.1042	:Entity110
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:240-358	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.1042	:Entity110
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:240-358	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.1042	:Entity110
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:240-358	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.1042	:Entity110
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:240-358	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.1042	:Entity110
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:178-288	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.5936	:Entity110
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:178-288	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.5936	:Entity110
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:178-288	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.5936	:Entity110
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:178-288	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.5936	:Entity110
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:178-288	Springfield Elementary School	ORG	SIMPSONS_113:105-135	0.5936	:Entity110
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_117:103-250	Springfield Elementary School	ORG	SIMPSONS_117:225-255	0.2466	:Entity110
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_117:103-250	Springfield Elementary School	ORG	SIMPSONS_117:225-255	0.2466	:Entity110
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_117:103-250	Springfield Elementary School	ORG	SIMPSONS_117:225-255	0.2466	:Entity110
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_117:103-250	Springfield Elementary School	ORG	SIMPSONS_117:225-255	0.2466	:Entity110
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_117:103-250	Springfield Elementary School	ORG	SIMPSONS_117:225-255	0.2466	:Entity110
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_120:128-229	Springfield Elementary School	ORG	SIMPSONS_120:205-235	0.2263	:Entity110
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_120:128-229	Springfield Elementary School	ORG	SIMPSONS_120:205-235	0.2263	:Entity110
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_120:128-229	Springfield Elementary School	ORG	SIMPSONS_120:205-235	0.2263	:Entity110
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_120:128-229	Springfield Elementary School	ORG	SIMPSONS_120:205-235	0.2263	:Entity110
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_120:128-229	Springfield Elementary School	ORG	SIMPSONS_120:205-235	0.2263	:Entity110
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:116-274	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.6672	:Entity110
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:116-274	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.6672	:Entity110
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:116-274	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.6672	:Entity110
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:116-274	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.6672	:Entity110
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:116-274	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.6672	:Entity110
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:205-362	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.9302	:Entity110
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:205-362	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.9302	:Entity110
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:205-362	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.9302	:Entity110
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:205-362	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.9302	:Entity110
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_121:205-362	Springfield Elementary School	ORG	SIMPSONS_121:189-219	0.9302	:Entity110
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:237-343	Springfield Elementary School	ORG	SIMPSONS_128:118-148	0.6321	:Entity110
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:237-343	Springfield Elementary School	ORG	SIMPSONS_128:118-148	0.6321	:Entity110
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:237-343	Springfield Elementary School	ORG	SIMPSONS_128:118-148	0.6321	:Entity110
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:237-343	Springfield Elementary School	ORG	SIMPSONS_128:118-148	0.6321	:Entity110
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:237-343	Springfield Elementary School	ORG	SIMPSONS_128:118-148	0.6321	:Entity110
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_130:173-309	Springfield Elementary School	ORG	SIMPSONS_130:158-188	0.4364	:Entity110
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_130:173-309	Springfield Elementary School	ORG	SIMPSONS_130:158-188	0.4364	:Entity110
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_130:173-309	Springfield Elementary School	ORG	SIMPSONS_130:158-188	0.4364	:Entity110
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_130:173-309	Springfield Elementary School	ORG	SIMPSONS_130:158-188	0.4364	:Entity110
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_130:173-309	Springfield Elementary School	ORG	SIMPSONS_130:158-188	0.4364	:Entity110
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:177-333	Springfield Elementary School	ORG	SIMPSONS_146:241-271	0.6554	:Entity110
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:177-333	Springfield Elementary School	ORG	SIMPSONS_146:241-271	0.6554	:Entity110
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:177-333	Springfield Elementary School	ORG	SIMPSONS_146:241-271	0.6554	:Entity110
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:177-333	Springfield Elementary School	ORG	SIMPSONS_146:241-271	0.6554	:Entity110
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:177-333	Springfield Elementary School	ORG	SIMPSONS_146:241-271	0.6554	:Entity110
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_149:175-301	Springfield Elementary School	ORG	SIMPSONS_149:102-132	0.1317	:Entity110
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_149:175-301	Springfield Elementary School	ORG	SIMPSONS_149:102-132	0.1317	:Entity110
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_149:175-301	Springfield Elementary School	ORG	SIMPSONS_149:102-132	0.1317	:Entity110
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_149:175-301	Springfield Elementary School	ORG	SIMPSONS_149:102-132	0.1317	:Entity110
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_149:175-301	Springfield Elementary School	ORG	SIMPSONS_149:102-132	0.1317	:Entity110
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_166:215-371	Springfield Elementary School	ORG	SIMPSONS_166:147-177	0.2007	:Entity110
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_166:215-371	Springfield Elementary School	ORG	SIMPSONS_166:147-177	0.2007	:Entity110
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_166:215-371	Springfield Elementary School	ORG	SIMPSONS_166:147-177	0.2007	:Entity110
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_166:215-371	Springfield Elementary School	ORG	SIMPSONS_166:147-177	0.2007	:Entity110
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_166:215-371	Springfield Elementary School	ORG	SIMPSONS_166:147-177	0.2007	:Entity110
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:194-304	Springfield Elementary School	ORG	SIMPSONS_168:126-156	0.8475	:Entity110
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:194-304	Springfield Elementary School	ORG	SIMPSONS_168:126-156	0.8475	:Entity110
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:194-304	Springfield Elementary School	ORG	SIMPSONS_168:126-156	0.8475	:Entity110
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:194-304	Springfield Elementary School	ORG	SIMPSONS_168:126-156	0.8475	:Entity110
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:194-304	Springfield Elementary School	ORG	SIMPSONS_168:126-156	0.8475	:Entity110
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_180:240-346	Springfield Elementary School	ORG	SIMPSONS_180:223-253	0.0246	:Entity110
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_180:240-346	Springfield Elementary School	ORG	SIMPSONS_180:223-253	0.0246	:Entity110
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_180:240-346	Springfield Elementary School	ORG	SIMPSONS_180:223-253	0.0246	:Entity110
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_180:240-346	Springfield Elementary School	ORG	SIMPSONS_180:223-253	0.0246	:Entity110
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_180:240-346	Springfield Elementary School	ORG	SIMPSONS_180:223-253	0.0246	:Entity110
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_193:185-334	Springfield Elementary School	ORG	SIMPSONS_193:214-244	0.6611	:Entity110
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_193:185-334	Springfield Elementary School	ORG	SIMPSONS_193:214-244	0.6611	:Entity110
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_193:185-334	Springfield Elementary School	ORG	SIMPSONS_193:214-244	0.6611	:Entity110
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_193:185-334	Springfield Elementary School	ORG	SIMPSONS_193:214-244	0.6611	:Entity110
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_193:185-334	Springfield Elementary School	ORG	SIMPSONS_193:214-244	0.6611	:Entity110
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_101:128-285	Springfield High School	ORG	SIMPSONS_101:210-234	0.5961	:Entity111
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_101:128-285	Springfield High School	ORG	SIMPSONS_101:210-234	0.5961	:Entity111
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_101:128-285	Springfield High School	ORG	SIMPSONS_101:210-234	0.5961	:Entity111
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_101:128-285	Springfield High School	ORG	SIMPSONS_101:210-234	0.5961	:Entity111
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_101:128-285	Springfield High School	ORG	SIMPSONS_101:210-234	0.5961	:Entity111
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_103:138-279	Springfield High School	ORG	SIMPSONS_103:186-210	0.9589	:Entity111
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_103:138-279	Springfield High School	ORG	SIMPSONS_103:186-210	0.9589	:Entity111
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_103:138-279	Springfield High School	ORG	SIMPSONS_103:186-210	0.9589	:Entity111
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_103:138-279	Springfield High School	ORG	SIMPSONS_103:186-210	0.9589	:Entity111
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_103:138-279	Springfield High School	ORG	SIMPSONS_103:186-210	0.9589	:Entity111
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_114:234-392	Springfield High School	ORG	SIMPSONS_114:220-244	0.0422	:Entity111
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_114:234-392	Springfield High School	ORG	SIMPSONS_114:220-244	0.0422	:Entity111
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_114:234-392	Springfield High School	ORG	SIMPSONS_114:220-244	0.0422	:Entity111
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_114:234-392	Springfield High School	ORG	SIMPSONS_114:220-244	0.0422	:Entity111
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_114:234-392	Springfield High School	ORG	SIMPSONS_114:220-244	0.0422	:Entity111
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_116:164-303	Springfield High School	ORG	SIMPSONS_116:162-186	0.4353	:Entity111
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_116:164-303	Springfield High School	ORG	SIMPSONS_116:162-186	0.4353	:Entity111
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_116:164-303	Springfield High School	ORG	SIMPSONS_116:162-186	0.4353	:Entity111
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_116:164-303	Springfield High School	ORG	SIMPSONS_116:162-186	0.4353	:Entity111
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_116:164-303	Springfield High School	ORG	SIMPSONS_116:162-186	0.4353	:Entity111
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_126:172-276	Springfield High School	ORG	SIMPSONS_126:120-144	0.6808	:Entity111
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_126:172-276	Springfield High School	ORG	SIMPSONS_126:120-144	0.6808	:Entity111
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_126:172-276	Springfield High School	ORG	SIMPSONS_126:120-144	0.6808	:Entity111
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_126:172-276	Springfield High School	ORG	SIMPSONS_126:120-144	0.6808	:Entity111
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_126:172-276	Springfield High School	ORG	SIMPSONS_126:120-144	0.6808	:Entity111
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_127:174-279	Springfield High School	ORG	SIMPSONS_127:178-202	0.5516	:Entity111
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_127:174-279	Springfield High School	ORG	SIMPSONS_127:178-202	0.5516	:Entity111
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_127:174-279	Springfield High School	ORG	SIMPSONS_127:178-202	0.5516	:Entity111
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_127:174-279	Springfield High School	ORG	SIMPSONS_127:178-202	0.5516	:Entity111
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_127:174-279	Springfield High School	ORG	SIMPSONS_127:178-202	0.5516	:Entity111
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:219-327	Springfield High School	ORG	SIMPSONS_128:187-211	0.8759	:Entity111
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:219-327	Springfield High School	ORG	SIMPSONS_128:187-211	0.8759	:Entity111
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:219-327	Springfield High School	ORG	SIMPSONS_128:187-211	0.8759	:Entity111
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:219-327	Springfield High School	ORG	SIMPSONS_128:187-211	0.8759	:Entity111
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:219-327	Springfield High School	ORG	SIMPSONS_128:187-211	0.8759	:Entity111
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_133:184-286	Springfield High School	ORG	SIMPSONS_133:161-185	0.8458	:Entity111
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_133:184-286	Springfield High School	ORG	SIMPSONS_133:161-185	0.8458	:Entity111
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_133:184-286	Springfield High School	ORG	SIMPSONS_133:161-185	0.8458	:Entity111
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_133:184-286	Springfield High School	ORG	SIMPSONS_133:161-185	0.8458	:Entity111
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_133:184-286	Springfield High School	ORG	SIMPSONS_133:161-185	0.8458	:Entity111
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_138:125-231	Springfield High School	ORG	SIMPSONS_138:206-230	0.9567	:Entity111
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_138:125-231	Springfield High School	ORG	SIMPSONS_138:206-230	0.9567	:Entity111
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_138:125-231	Springfield High School	ORG	SIMPSONS_138:206-230	0.9567	:Entity111
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_138:125-231	Springfield High School	ORG	SIMPSONS_138:206-230	0.9567	:Entity111
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_138:125-231	Springfield High School	ORG	SIMPSONS_138:206-230	0.9567	:Entity111
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_147:248-355	Springfield High School	ORG	SIMPSONS_147:185-209	0.0597	:Entity111
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_147:248-355	Springfield High School	ORG	SIMPSONS_147:185-209	0.0597	:Entity111
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_147:248-355	Springfield High School	ORG	SIMPSONS_147:185-209	0.0597	:Entity111
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_147:248-355	Springfield High School	ORG	SIMPSONS_147:185-209	0.0597	:Entity111
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_147:248-355	Springfield High School	ORG	SIMPSONS_147:185-209	0.0597	:Entity111
CSSF17_ENG_afddc4ed21_899fb7b77527	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:225-381	Springfield High School	ORG	SIMPSONS_154:114-138	0.0627	:Entity111
CSSF17_ENG_afddc4ed21_98c8da05aca8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:225-381	Springfield High School	ORG	SIMPSONS_154:114-138	0.0627	:Entity111
CSSF17_ENG_afddc4ed21_645d5f517a84	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:225-381	Springfield High School	ORG	SIMPSONS_154:114-138	0.0627	:Entity111
CSSF17_ENG_afddc4ed21_1c191d37052d	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:225-381	Springfield High School	ORG	SIMPSONS_154:114-138	0.0627	:Entity111
CSSF17_ENG_afddc4ed21_48fe71607ee8	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:225-381	Springfield High School	ORG	SIMPSONS_154:114-138	0.0627	:Entity111
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:206-334	Springfield High School	ORG	SIMPSONS_168:184-208	0.3305	:Entity111
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:206-334	Springfield High School	ORG	SIMPSONS_168:184-208	0.3305	:Entity111
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:206-334	Springfield High School	ORG	SIMPSONS_168:184-208	0.3305	:Entity111
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:206-334	Springfield High School	ORG	SIMPSONS_168:184-208	0.3305	:Entity111
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_168:206-334	Springfield High School	ORG	SIMPSONS_168:184-208	0.3305	:Entity111
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_179:215-340	Springfield High School	ORG	SIMPSONS_179:174-198	0.4086	:Entity111
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_179:215-340	Springfield High School	ORG	SIMPSONS_179:174-198	0.4086	:Entity111
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_179:215-340	Springfield High School	ORG	SIMPSONS_179:174-198	0.4086	:Entity111
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_179:215-340	Springfield High School	ORG	SIMPSONS_179:174-198	0.4086	:Entity111
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_179:215-340	Springfield High School	ORG	SIMPSONS_179:174-198	0.4086	:Entity111
CSSF17_ENG_afddc4ed21_6cfda670ab40	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_195:222-334	Springfield High School	ORG	SIMPSONS_195:248-272	0.4398	:Entity111
CSSF17_ENG_afddc4ed21_be476e3f0554	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_195:222-334	Springfield High School	ORG	SIMPSONS_195:248-272	0.4398	:Entity111
CSSF17_ENG_afddc4ed21_063a214393c2	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_195:222-334	Springfield High School	ORG	SIMPSONS_195:248-272	0.4398	:Entity111
CSSF17_ENG_afddc4ed21_8a9f952d62da	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_195:222-334	Springfield High School	ORG	SIMPSONS_195:248-272	0.4398	:Entity111
CSSF17_ENG_afddc4ed21_a036e7682fe6	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_195:222-334	Springfield High School	ORG	SIMPSONS_195:248-272	0.4398	:Entity111
CSSF17_ENG_afddc4ed21_331fc5a85079	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_196:239-395	Springfield High School	ORG	SIMPSONS_196:219-243	0.7583	:Entity111
CSSF17_ENG_afddc4ed21_facbc244ea47	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_196:239-395	Springfield High School	ORG	SIMPSONS_196:219-243	0.7583	:Entity111
CSSF17_ENG_afddc4ed21_91ff2b9a6598	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_196:239-395	Springfield High School	ORG	SIMPSONS_196:219-243	0.7583	:Entity111
CSSF17_ENG_afddc4ed21_72fda4daa127	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_196:239-395	Springfield High School	ORG	SIMPSONS_196:219-243	0.7583	:Entity111
CSSF17_ENG_afddc4ed21_09ef50c1a3bf	per:schools_attended	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_196:239-395	Springfield High School	ORG	SIMPSONS_196:219-243	0.7583	:Entity111
CSSF17_ENG_3851d3b3a1	per:cities_of_residence	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_100:118-224	Boston	GPE	SIMPSONS_100:110-117	0.0387	:Entity201
CSSF17_ENG_3851d3b3a1	per:cities_of_residence	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_112:179-307	Boston	GPE	SIMPSONS_112:105-112	0.0974	:Entity201
CSSF17_ENG_65087022a9	per:dislikes	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_114:166-173	Boston	GPE	SIMPSONS_114:166-173	0.2289	:Entity201
CSSF17_ENG_3851d3b3a1	per:cities_of_residence	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:136-267	Boston	GPE	SIMPSONS_128:192-199	0.6538	:Entity201
CSSF17_ENG_65087022a9	per:dislikes	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_139:155-162	Boston	GPE	SIMPSONS_139:155-162	0.7999	:Entity201
CSSF17_ENG_3851d3b3a1	per:cities_of_residence	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:191-313	Boston	GPE	SIMPSONS_146:107-114	0.1987	:Entity201
CSSF17_ENG_3851d3b3a1	per:cities_of_residence	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_150:147-292	Boston	GPE	SIMPSONS_150:135-142	0.2928	:Entity201
CSSF17_ENG_65087022a9	per:dislikes	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_156:127-134	Boston	GPE	SIMPSONS_156:127-134	0.5030	:Entity201
CSSF17_ENG_65087022a9	per:dislikes	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_164:174-181	Boston	GPE	SIMPSONS_164:174-181	0.8664	:Entity201
CSSF17_ENG_65087022a9	per:dislikes	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_173:154-161	Boston	GPE	SIMPSONS_173:154-161	0.6896	:Entity201
CSSF17_ENG_cc8f9efc40	per:conflict.attack_attacker	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_113:207-213,SIMPSONS_113:135-257	bombing	CONFLICT.ATTACK	SIMPSONS_113:243-251	0.4068	:Event101
CSSF17_ENG_cc8f9efc40	per:conflict.attack_attacker	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_127:133-139,SIMPSONS_127:160-268	bombing	CONFLICT.ATTACK	SIMPSONS_127:160-168	0.4955	:Event101
CSSF17_ENG_cc8f9efc40	per:conflict.attack_attacker	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_139:197-203,SIMPSONS_139:104-246	bombing	CONFLICT.ATTACK	SIMPSONS_139:240-248	0.1731	:Event101
CSSF17_ENG_cc8f9efc40	per:conflict.attack_attacker	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_173:159-165,SIMPSONS_173:153-304	bombing	CONFLICT.ATTACK	SIMPSONS_173:126-134	0.2050	:Event101
CSSF17_ENG_cc8f9efc40	per:conflict.attack_attacker	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_174:163-169,SIMPSONS_174:164-307	bombing	CONFLICT.ATTACK	SIMPSONS_174:228-236	0.8719	:Event101
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_100:118-224	Homer	PER	SIMPSONS_100:220-226	0.0387	:Entity101
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_100:118-224	Homer	PER	SIMPSONS_100:220-226	0.0387	:Entity101
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_100:118-224	Homer	PER	SIMPSONS_100:220-226	0.0387	:Entity101
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_100:118-224	Homer	PER	SIMPSONS_100:220-226	0.0387	:Entity101
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_100:118-224	Homer	PER	SIMPSONS_100:220-226	0.0387	:Entity101
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_112:179-307	Homer	PER	SIMPSONS_112:152-158	0.0974	:Entity101
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_112:179-307	Homer	PER	SIMPSONS_112:152-158	0.0974	:Entity101
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_112:179-307	Homer	PER	SIMPSONS_112:152-158	0.0974	:Entity101
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_112:179-307	Homer	PER	SIMPSONS_112:152-158	0.0974	:Entity101
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_112:179-307	Homer	PER	SIMPSONS_112:152-158	0.0974	:Entity101
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:136-267	Homer	PER	SIMPSONS_128:220-226	0.6538	:Entity101
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:136-267	Homer	PER	SIMPSONS_128:220-226	0.6538	:Entity101
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:136-267	Homer	PER	SIMPSONS_128:220-226	0.6538	:Entity101
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:136-267	Homer	PER	SIMPSONS_128:220-226	0.6538	:Entity101
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_128:136-267	Homer	PER	SIMPSONS_128:220-226	0.6538	:Entity101
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:191-313	Homer	PER	SIMPSONS_146:113-119	0.1987	:Entity101
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:191-313	Homer	PER	SIMPSONS_146:113-119	0.1987	:Entity101
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:191-313	Homer	PER	SIMPSONS_146:113-119	0.1987	:Entity101
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:191-313	Homer	PER	SIMPSONS_146:113-119	0.1987	:Entity101
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_146:191-313	Homer	PER	SIMPSONS_146:113-119	0.1987	:Entity101
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_150:147-292	Homer	PER	SIMPSONS_150:243-249	0.2928	:Entity101
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_150:147-292	Homer	PER	SIMPSONS_150:243-249	0.2928	:Entity101
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_150:147-292	Homer	PER	SIMPSONS_150:243-249	0.2928	:Entity101
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_150:147-292	Homer	PER	SIMPSONS_150:243-249	0.2928	:Entity101
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_150:147-292	Homer	PER	SIMPSONS_150:243-249	0.2928	:Entity101
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:188-337	Lisa Simpson	PER	SIMPSONS_154:167-180	0.6200	:Entity104
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:188-337	Lisa Simpson	PER	SIMPSONS_154:167-180	0.6200	:Entity104
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:188-337	Lisa Simpson	PER	SIMPSONS_154:167-180	0.6200	:Entity104
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:188-337	Lisa Simpson	PER	SIMPSONS_154:167-180	0.6200	:Entity104
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_154:188-337	Lisa Simpson	PER	SIMPSONS_154:167-180	0.6200	:Entity104
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_175:239-351	Lisa Simpson	PER	SIMPSONS_175:197-210	0.0354	:Entity104
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_175:239-351	Lisa Simpson	PER	SIMPSONS_175:197-210	0.0354	:Entity104
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_175:239-351	Lisa Simpson	PER	SIMPSONS_175:197-210	0.0354	:Entity104
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_175:239-351	Lisa Simpson	PER	SIMPSONS_175:197-210	0.0354	:Entity104
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_175:239-351	Lisa Simpson	PER	SIMPSONS_175:197-210	0.0354	:Entity104
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_191:143-268	Lisa Simpson	PER	SIMPSONS_191:159-172	0.1279	:Entity104
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_191:143-268	Lisa Simpson	PER	SIMPSONS_191:159-172	0.1279	:Entity104
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_191:143-268	Lisa Simpson	PER	SIMPSONS_191:159-172	0.1279	:Entity104
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_191:143-268	Lisa Simpson	PER	SIMPSONS_191:159-172	0.1279	:Entity104
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_191:143-268	Lisa Simpson	PER	SIMPSONS_191:159-172	0.1279	:Entity104
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_198:207-313	Lisa Simpson	PER	SIMPSONS_198:184-197	0.7636	:Entity104
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_198:207-313	Lisa Simpson	PER	SIMPSONS_198:184-197	0.7636	:Entity104
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_198:207-313	Lisa Simpson	PER	SIMPSONS_198:184-197	0.7636	:Entity104
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_198:207-313	Lisa Simpson	PER	SIMPSONS_198:184-197	0.7636	:Entity104
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_198:207-313	Lisa Simpson	PER	SIMPSONS_198:184-197	0.7636	:Entity104
CSSF17_ENG_3851d3b3a1_69d7ebd6fbe7	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_199:175-286	Lisa Simpson	PER	SIMPSONS_199:238-251	0.3405	:Entity104
CSSF17_ENG_3851d3b3a1_cadb6036ad15	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_199:175-286	Lisa Simpson	PER	SIMPSONS_199:238-251	0.3405	:Entity104
CSSF17_ENG_3851d3b3a1_da39e3b14d19	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_199:175-286	Lisa Simpson	PER	SIMPSONS_199:238-251	0.3405	:Entity104
CSSF17_ENG_3851d3b3a1_e3213b4d4ed5	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_199:175-286	Lisa Simpson	PER	SIMPSONS_199:238-251	0.3405	:Entity104
CSSF17_ENG_3851d3b3a1_78ea11b45261	gpe:residents_of_city	SCORER_TS_MERGE_AND_SPLIT_CMPLX	SIMPSONS_199:175-286	Lisa Simpson	PER	SIMPSONS_199:238-251	0.3405	:Entity104
