CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_011:119-172	Bart	PER	SIMPSONS_011:130-135	0.1178	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_015:89-118	Bart Simpson	PER	SIMPSONS_015:14-27	0.5447	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_017:150-191	Bart	PER	SIMPSONS_017:53-58	0.2733	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_018:35-53	Bart Simpson	PER	SIMPSONS_018:72-85	0.2557	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_020:9-28	Bart Simpson	PER	SIMPSONS_020:46-59	0.8334	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_011:141-184	Lisa	PER	SIMPSONS_011:138-143	0.9999	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_012:91-99	Lisa	PER	SIMPSONS_012:90-95	0.8116	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_016:41-64	Lisa	PER	SIMPSONS_016:72-77	0.1749	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_018:121-171	Lisa	PER	SIMPSONS_018:77-82	0.4358	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_018:140-168	Lisa	PER	SIMPSONS_018:77-82	0.9651	:Entity103
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_011:9-17	Lisa	PER	SIMPSONS_011:138-143	0.0123	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_012:67-112	Lisa Simpson	PER	SIMPSONS_012:81-94	0.9864	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_013:57-105	Lisa Simpson	PER	SIMPSONS_013:56-69	0.3379	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_015:10-22	Lisa Simpson	PER	SIMPSONS_015:102-115	0.1891	:Entity104
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_SPLIT	SIMPSONS_015:27-29	Lisa Simpson	PER	SIMPSONS_015:102-115	0.1298	:Entity104
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:60-63	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.1492	:Entity110
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:60-63	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.1492	:Entity110
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:60-63	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.1492	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:60-63	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.1492	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:60-63	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.1492	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:102-152	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.7211	:Entity110
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:102-152	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.7211	:Entity110
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:102-152	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.7211	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:102-152	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.7211	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:102-152	Springfield Elementary School	ORG	SIMPSONS_011:67-97	0.7211	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_013:138-172	Springfield Elementary School	ORG	SIMPSONS_013:146-176	0.0282	:Entity110
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_013:138-172	Springfield Elementary School	ORG	SIMPSONS_013:146-176	0.0282	:Entity110
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_013:138-172	Springfield Elementary School	ORG	SIMPSONS_013:146-176	0.0282	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_013:138-172	Springfield Elementary School	ORG	SIMPSONS_013:146-176	0.0282	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_013:138-172	Springfield Elementary School	ORG	SIMPSONS_013:146-176	0.0282	:Entity110
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:113-148	Springfield Elementary School	ORG	SIMPSONS_014:118-148	0.0036	:Entity110
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:113-148	Springfield Elementary School	ORG	SIMPSONS_014:118-148	0.0036	:Entity110
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:113-148	Springfield Elementary School	ORG	SIMPSONS_014:118-148	0.0036	:Entity110
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:113-148	Springfield Elementary School	ORG	SIMPSONS_014:118-148	0.0036	:Entity110
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:113-148	Springfield Elementary School	ORG	SIMPSONS_014:118-148	0.0036	:Entity110
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:7-63	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.9509	:Entity110
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:7-63	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.9509	:Entity110
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:7-63	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.9509	:Entity110
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:7-63	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.9509	:Entity110
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:7-63	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.9509	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:8-14	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.0158	:Entity110
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:8-14	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.0158	:Entity110
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:8-14	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.0158	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:8-14	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.0158	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:8-14	Springfield Elementary School	ORG	SIMPSONS_015:54-84	0.0158	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:115-174	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5617	:Entity110
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:115-174	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5617	:Entity110
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:115-174	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5617	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:115-174	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5617	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:115-174	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5617	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:9-49	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5769	:Entity110
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:9-49	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5769	:Entity110
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:9-49	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5769	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:9-49	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5769	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:9-49	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.5769	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:34-69	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.4448	:Entity110
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:34-69	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.4448	:Entity110
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:34-69	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.4448	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:34-69	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.4448	:Entity110
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:34-69	Springfield Elementary School	ORG	SIMPSONS_016:10-40	0.4448	:Entity110
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:24-72	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.6733	:Entity110
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:24-72	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.6733	:Entity110
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:24-72	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.6733	:Entity110
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:24-72	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.6733	:Entity110
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:24-72	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.6733	:Entity110
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:58-64	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.0584	:Entity110
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:58-64	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.0584	:Entity110
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:58-64	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.0584	:Entity110
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:58-64	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.0584	:Entity110
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:58-64	Springfield Elementary School	ORG	SIMPSONS_017:22-52	0.0584	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:75-134	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.3753	:Entity110
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:75-134	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.3753	:Entity110
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:75-134	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.3753	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:75-134	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.3753	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:75-134	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.3753	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:105-140	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.6050	:Entity110
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:105-140	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.6050	:Entity110
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:105-140	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.6050	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:105-140	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.6050	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_018:105-140	Springfield Elementary School	ORG	SIMPSONS_018:103-133	0.6050	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:18-30	Springfield Elementary School	ORG	SIMPSONS_019:74-104	0.6980	:Entity110
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:18-30	Springfield Elementary School	ORG	SIMPSONS_019:74-104	0.6980	:Entity110
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:18-30	Springfield Elementary School	ORG	SIMPSONS_019:74-104	0.6980	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:18-30	Springfield Elementary School	ORG	SIMPSONS_019:74-104	0.6980	:Entity110
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:18-30	Springfield Elementary School	ORG	SIMPSONS_019:74-104	0.6980	:Entity110
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:22-59	Springfield Elementary School	ORG	SIMPSONS_020:41-71	0.3759	:Entity110
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:22-59	Springfield Elementary School	ORG	SIMPSONS_020:41-71	0.3759	:Entity110
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:22-59	Springfield Elementary School	ORG	SIMPSONS_020:41-71	0.3759	:Entity110
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:22-59	Springfield Elementary School	ORG	SIMPSONS_020:41-71	0.3759	:Entity110
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:22-59	Springfield Elementary School	ORG	SIMPSONS_020:41-71	0.3759	:Entity110
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:75-104	Springfield High School	ORG	SIMPSONS_011:48-72	0.8404	:Entity111
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:75-104	Springfield High School	ORG	SIMPSONS_011:48-72	0.8404	:Entity111
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:75-104	Springfield High School	ORG	SIMPSONS_011:48-72	0.8404	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:75-104	Springfield High School	ORG	SIMPSONS_011:48-72	0.8404	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_011:75-104	Springfield High School	ORG	SIMPSONS_011:48-72	0.8404	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_012:84-86	Springfield High School	ORG	SIMPSONS_012:4-28	0.4244	:Entity111
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_012:84-86	Springfield High School	ORG	SIMPSONS_012:4-28	0.4244	:Entity111
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_012:84-86	Springfield High School	ORG	SIMPSONS_012:4-28	0.4244	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_012:84-86	Springfield High School	ORG	SIMPSONS_012:4-28	0.4244	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_012:84-86	Springfield High School	ORG	SIMPSONS_012:4-28	0.4244	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:15-36	Springfield High School	ORG	SIMPSONS_014:36-60	0.7285	:Entity111
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:15-36	Springfield High School	ORG	SIMPSONS_014:36-60	0.7285	:Entity111
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:15-36	Springfield High School	ORG	SIMPSONS_014:36-60	0.7285	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:15-36	Springfield High School	ORG	SIMPSONS_014:36-60	0.7285	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_014:15-36	Springfield High School	ORG	SIMPSONS_014:36-60	0.7285	:Entity111
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:147-171	Springfield High School	ORG	SIMPSONS_015:85-109	0.0162	:Entity111
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:147-171	Springfield High School	ORG	SIMPSONS_015:85-109	0.0162	:Entity111
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:147-171	Springfield High School	ORG	SIMPSONS_015:85-109	0.0162	:Entity111
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:147-171	Springfield High School	ORG	SIMPSONS_015:85-109	0.0162	:Entity111
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_015:147-171	Springfield High School	ORG	SIMPSONS_015:85-109	0.0162	:Entity111
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:72-79	Springfield High School	ORG	SIMPSONS_016:149-173	0.9088	:Entity111
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:72-79	Springfield High School	ORG	SIMPSONS_016:149-173	0.9088	:Entity111
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:72-79	Springfield High School	ORG	SIMPSONS_016:149-173	0.9088	:Entity111
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:72-79	Springfield High School	ORG	SIMPSONS_016:149-173	0.9088	:Entity111
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:72-79	Springfield High School	ORG	SIMPSONS_016:149-173	0.9088	:Entity111
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:150-181	Springfield High School	ORG	SIMPSONS_016:149-173	0.9943	:Entity111
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:150-181	Springfield High School	ORG	SIMPSONS_016:149-173	0.9943	:Entity111
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:150-181	Springfield High School	ORG	SIMPSONS_016:149-173	0.9943	:Entity111
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:150-181	Springfield High School	ORG	SIMPSONS_016:149-173	0.9943	:Entity111
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:150-181	Springfield High School	ORG	SIMPSONS_016:149-173	0.9943	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:139-139	Springfield High School	ORG	SIMPSONS_016:149-173	0.3079	:Entity111
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:139-139	Springfield High School	ORG	SIMPSONS_016:149-173	0.3079	:Entity111
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:139-139	Springfield High School	ORG	SIMPSONS_016:149-173	0.3079	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:139-139	Springfield High School	ORG	SIMPSONS_016:149-173	0.3079	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_016:139-139	Springfield High School	ORG	SIMPSONS_016:149-173	0.3079	:Entity111
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:38-47	Springfield High School	ORG	SIMPSONS_017:125-149	0.4268	:Entity111
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:38-47	Springfield High School	ORG	SIMPSONS_017:125-149	0.4268	:Entity111
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:38-47	Springfield High School	ORG	SIMPSONS_017:125-149	0.4268	:Entity111
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:38-47	Springfield High School	ORG	SIMPSONS_017:125-149	0.4268	:Entity111
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_017:38-47	Springfield High School	ORG	SIMPSONS_017:125-149	0.4268	:Entity111
CSSF17_ENG_afddc4ed21_3b46ec5ede57	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:119-177	Springfield High School	ORG	SIMPSONS_019:33-57	0.6023	:Entity111
CSSF17_ENG_afddc4ed21_18ee585af031	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:119-177	Springfield High School	ORG	SIMPSONS_019:33-57	0.6023	:Entity111
CSSF17_ENG_afddc4ed21_23ae2bc83fbd	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:119-177	Springfield High School	ORG	SIMPSONS_019:33-57	0.6023	:Entity111
CSSF17_ENG_afddc4ed21_4f03d45bc20a	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:119-177	Springfield High School	ORG	SIMPSONS_019:33-57	0.6023	:Entity111
CSSF17_ENG_afddc4ed21_f4ad4eed22ad	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:119-177	Springfield High School	ORG	SIMPSONS_019:33-57	0.6023	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:3-28	Springfield High School	ORG	SIMPSONS_019:33-57	0.1723	:Entity111
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:3-28	Springfield High School	ORG	SIMPSONS_019:33-57	0.1723	:Entity111
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:3-28	Springfield High School	ORG	SIMPSONS_019:33-57	0.1723	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:3-28	Springfield High School	ORG	SIMPSONS_019:33-57	0.1723	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:3-28	Springfield High School	ORG	SIMPSONS_019:33-57	0.1723	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:22-26	Springfield High School	ORG	SIMPSONS_019:33-57	0.1451	:Entity111
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:22-26	Springfield High School	ORG	SIMPSONS_019:33-57	0.1451	:Entity111
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:22-26	Springfield High School	ORG	SIMPSONS_019:33-57	0.1451	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:22-26	Springfield High School	ORG	SIMPSONS_019:33-57	0.1451	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:22-26	Springfield High School	ORG	SIMPSONS_019:33-57	0.1451	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:51-76	Springfield High School	ORG	SIMPSONS_019:33-57	0.7091	:Entity111
CSSF17_ENG_afddc4ed21_3f7b77574583	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:51-76	Springfield High School	ORG	SIMPSONS_019:33-57	0.7091	:Entity111
CSSF17_ENG_afddc4ed21_bc49f811f307	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:51-76	Springfield High School	ORG	SIMPSONS_019:33-57	0.7091	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:51-76	Springfield High School	ORG	SIMPSONS_019:33-57	0.7091	:Entity111
CSSF17_ENG_afddc4ed21_0b413ff323e6	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:51-76	Springfield High School	ORG	SIMPSONS_019:33-57	0.7091	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:37-37	Springfield High School	ORG	SIMPSONS_019:33-57	0.0916	:Entity111
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:37-37	Springfield High School	ORG	SIMPSONS_019:33-57	0.0916	:Entity111
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:37-37	Springfield High School	ORG	SIMPSONS_019:33-57	0.0916	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:37-37	Springfield High School	ORG	SIMPSONS_019:33-57	0.0916	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:37-37	Springfield High School	ORG	SIMPSONS_019:33-57	0.0916	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:60-117	Springfield High School	ORG	SIMPSONS_019:33-57	0.0782	:Entity111
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:60-117	Springfield High School	ORG	SIMPSONS_019:33-57	0.0782	:Entity111
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:60-117	Springfield High School	ORG	SIMPSONS_019:33-57	0.0782	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:60-117	Springfield High School	ORG	SIMPSONS_019:33-57	0.0782	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_019:60-117	Springfield High School	ORG	SIMPSONS_019:33-57	0.0782	:Entity111
CSSF17_ENG_afddc4ed21_b1d009063e02	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:7-62	Springfield High School	ORG	SIMPSONS_020:140-164	0.6707	:Entity111
CSSF17_ENG_afddc4ed21_1fa227e2e937	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:7-62	Springfield High School	ORG	SIMPSONS_020:140-164	0.6707	:Entity111
CSSF17_ENG_afddc4ed21_2d21b0131619	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:7-62	Springfield High School	ORG	SIMPSONS_020:140-164	0.6707	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:7-62	Springfield High School	ORG	SIMPSONS_020:140-164	0.6707	:Entity111
CSSF17_ENG_afddc4ed21_519d8ecfd43c	per:schools_attended	SCORER_TS_SPLIT	SIMPSONS_020:7-62	Springfield High School	ORG	SIMPSONS_020:140-164	0.6707	:Entity111
