CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE	SIMPSONS_115:108-221	Lisa Simpson	PER	SIMPSONS_115:239-252	0.8917	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE	SIMPSONS_129:113-259	Lisa Simpson	PER	SIMPSONS_129:197-210	0.5662	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE	SIMPSONS_161:136-268	Bart	PER	SIMPSONS_161:214-219	0.6773	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE	SIMPSONS_188:103-205	Lisa Simpson	PER	SIMPSONS_188:164-177	0.5045	:Entity102
CSSF17_ENG_afddc4ed21	per:children	SCORER_TS_MERGE	SIMPSONS_197:170-303	Lisa Simpson	PER	SIMPSONS_197:201-214	0.0557	:Entity102
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_109:104-205	Springfield Elementary School	ORG	SIMPSONS_109:114-144	0.0053	:Entity110
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_109:104-205	Springfield Elementary School	ORG	SIMPSONS_109:114-144	0.0053	:Entity110
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_109:104-205	Springfield Elementary School	ORG	SIMPSONS_109:114-144	0.0053	:Entity110
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_109:104-205	Springfield Elementary School	ORG	SIMPSONS_109:114-144	0.0053	:Entity110
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_109:104-205	Springfield Elementary School	ORG	SIMPSONS_109:114-144	0.0053	:Entity110
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_132:228-367	Springfield Elementary School	ORG	SIMPSONS_132:190-220	0.4363	:Entity110
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_132:228-367	Springfield Elementary School	ORG	SIMPSONS_132:190-220	0.4363	:Entity110
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_132:228-367	Springfield Elementary School	ORG	SIMPSONS_132:190-220	0.4363	:Entity110
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_132:228-367	Springfield Elementary School	ORG	SIMPSONS_132:190-220	0.4363	:Entity110
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_132:228-367	Springfield Elementary School	ORG	SIMPSONS_132:190-220	0.4363	:Entity110
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_158:170-291	Springfield Elementary School	ORG	SIMPSONS_158:200-230	0.2034	:Entity110
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_158:170-291	Springfield Elementary School	ORG	SIMPSONS_158:200-230	0.2034	:Entity110
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_158:170-291	Springfield Elementary School	ORG	SIMPSONS_158:200-230	0.2034	:Entity110
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_158:170-291	Springfield Elementary School	ORG	SIMPSONS_158:200-230	0.2034	:Entity110
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_158:170-291	Springfield Elementary School	ORG	SIMPSONS_158:200-230	0.2034	:Entity110
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_183:208-342	Springfield Elementary School	ORG	SIMPSONS_183:208-238	0.9446	:Entity110
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_183:208-342	Springfield Elementary School	ORG	SIMPSONS_183:208-238	0.9446	:Entity110
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_183:208-342	Springfield Elementary School	ORG	SIMPSONS_183:208-238	0.9446	:Entity110
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_183:208-342	Springfield Elementary School	ORG	SIMPSONS_183:208-238	0.9446	:Entity110
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_183:208-342	Springfield Elementary School	ORG	SIMPSONS_183:208-238	0.9446	:Entity110
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_189:113-239	Springfield Elementary School	ORG	SIMPSONS_189:138-168	0.0479	:Entity110
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_189:113-239	Springfield Elementary School	ORG	SIMPSONS_189:138-168	0.0479	:Entity110
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_189:113-239	Springfield Elementary School	ORG	SIMPSONS_189:138-168	0.0479	:Entity110
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_189:113-239	Springfield Elementary School	ORG	SIMPSONS_189:138-168	0.0479	:Entity110
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_189:113-239	Springfield Elementary School	ORG	SIMPSONS_189:138-168	0.0479	:Entity110
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_105:112-262	Springfield High School	ORG	SIMPSONS_105:244-268	0.7164	:Entity111
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_105:112-262	Springfield High School	ORG	SIMPSONS_105:244-268	0.7164	:Entity111
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_105:112-262	Springfield High School	ORG	SIMPSONS_105:244-268	0.7164	:Entity111
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_105:112-262	Springfield High School	ORG	SIMPSONS_105:244-268	0.7164	:Entity111
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_105:112-262	Springfield High School	ORG	SIMPSONS_105:244-268	0.7164	:Entity111
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_126:140-239	Springfield High School	ORG	SIMPSONS_126:149-173	0.5649	:Entity111
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_126:140-239	Springfield High School	ORG	SIMPSONS_126:149-173	0.5649	:Entity111
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_126:140-239	Springfield High School	ORG	SIMPSONS_126:149-173	0.5649	:Entity111
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_126:140-239	Springfield High School	ORG	SIMPSONS_126:149-173	0.5649	:Entity111
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_126:140-239	Springfield High School	ORG	SIMPSONS_126:149-173	0.5649	:Entity111
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:163-312	Springfield High School	ORG	SIMPSONS_155:136-160	0.1636	:Entity111
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:163-312	Springfield High School	ORG	SIMPSONS_155:136-160	0.1636	:Entity111
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:163-312	Springfield High School	ORG	SIMPSONS_155:136-160	0.1636	:Entity111
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:163-312	Springfield High School	ORG	SIMPSONS_155:136-160	0.1636	:Entity111
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:163-312	Springfield High School	ORG	SIMPSONS_155:136-160	0.1636	:Entity111
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:177-329	Springfield High School	ORG	SIMPSONS_155:136-160	0.1764	:Entity111
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:177-329	Springfield High School	ORG	SIMPSONS_155:136-160	0.1764	:Entity111
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:177-329	Springfield High School	ORG	SIMPSONS_155:136-160	0.1764	:Entity111
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:177-329	Springfield High School	ORG	SIMPSONS_155:136-160	0.1764	:Entity111
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_155:177-329	Springfield High School	ORG	SIMPSONS_155:136-160	0.1764	:Entity111
CSSF17_ENG_afddc4ed21_d49a6c1c0583	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_199:248-405	Springfield High School	ORG	SIMPSONS_199:127-151	0.2585	:Entity111
CSSF17_ENG_afddc4ed21_4cd3ca972bed	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_199:248-405	Springfield High School	ORG	SIMPSONS_199:127-151	0.2585	:Entity111
CSSF17_ENG_afddc4ed21_5b79f4925768	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_199:248-405	Springfield High School	ORG	SIMPSONS_199:127-151	0.2585	:Entity111
CSSF17_ENG_afddc4ed21_3ab6330943d2	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_199:248-405	Springfield High School	ORG	SIMPSONS_199:127-151	0.2585	:Entity111
CSSF17_ENG_afddc4ed21_6f407487d087	per:schools_attended	SCORER_TS_MERGE	SIMPSONS_199:248-405	Springfield High School	ORG	SIMPSONS_199:127-151	0.2585	:Entity111
